### ISSUE TITLE
Plugin doesn't start

### ISSUE THREAD

**Issue by theslash** [sweebee/pimatic-aqara#5]
Hi, I get this when I start Pimatic with Debug in the Aqara Plugin enabled:

21:46:45.464 [pimatic] info: Loading plugin: "pimatic-aqara" (0.4.4)
21:46:45.469 [pimatic] debug: debug is true in plugin config, showing debug output for pimatic-aqara.
21:46:45.495 [pimatic] error: this is not a typed array.
21:46:45.538 [pimatic] debug: TypeError: this is not a typed array.
21:46:45.538 [pimatic] debug:>    at Function.from (native)
21:46:45.538 [pimatic] debug:>    at Object.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-aqara/lumi-aqara/constants.js:6:23)
21:46:45.538 [pimatic] debug:>    at Module._compile (module.js:409:26)
21:46:45.538 [pimatic] debug:>    at Object.Module._extensions..js (module.js:416:10)
21:46:45.538 [pimatic] debug:>    at Module.load (/home/pi/pimatic-app/node_modules/pimatic-lcd/node_modules/i2c-lcd/node_modules/i2c/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
21:46:45.538 [pimatic] debug:>    at Function.Module._load (module.js:300:12)
21:46:45.538 [pimatic] debug:>    at Module.require (module.js:353:17)
21:46:45.538 [pimatic] debug:>    at require (internal/module.js:12:17)
21:46:45.538 [pimatic] debug:>    at Object.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-aqara/lumi-aqara/index.js:15:16)
21:46:45.538 [pimatic] debug:>    at Module._compile (module.js:409:26)
21:46:45.538 [pimatic] debug:>    at Object.Module._extensions..js (module.js:416:10)
21:46:45.538 [pimatic] debug:>    at Module.load (/home/pi/pimatic-app/node_modules/pimatic-lcd/node_modules/i2c-lcd/node_modules/i2c/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
21:46:45.538 [pimatic] debug:>    at Function.Module._load (module.js:300:12)
21:46:45.538 [pimatic] debug:>    at Module.require (module.js:353:17)
21:46:45.538 [pimatic] debug:>    at require (internal/module.js:12:17)
21:46:45.538 [pimatic] debug:>    at module.exports (/home/pi/pimatic-app/node_modules/pimatic-aqara/aqara.coffee:5:15)
21:46:45.538 [pimatic] debug:>    at PluginManager.loadPlugin (/home/pi/pimatic-app/node_modules/pimatic/lib/plugins.coffee:83:16)
21:46:45.538 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic/lib/plugins.coffee:485:25
21:46:45.538 [pimatic] debug:>    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/util.js:16:23)
21:46:45.538 [pimatic] debug:>    at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:512:31)
21:46:45.538 [pimatic] debug:>    at Promise._settlePromise (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:569:18)
21:46:45.538 [pimatic] debug:>    at Promise._settlePromiseCtx (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:606:10)
21:46:45.538 [pimatic] debug:>    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:138:12)
21:46:45.538 [pimatic] debug:>    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:143:10)
21:46:45.538 [pimatic] debug:>    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:17:14)
21:46:45.538 [pimatic] debug:>    at processImmediate [as _immediateCallback] (timers.js:383:17)

I checked the password and it should be ok, what I was wondering: Do I never have to enter the IP of the gateway anywhere?

**Comment by theslash** [comment]
Nevermind, updating Node to 4.8.5 solved the issue
